#1-Case_Study_Inferential Statistics

In [ ]:
import pandas as pd

bookseller_df = pd.read_csv('bookseller.csv')

bookseller_df.head()

   S.No        Date  Number of Books Sold
0     1  01-01-2020                    90
1     2  02-01-2020                   100
2     3  03-01-2020                   100
3     4  04-01-2020                    97
4     5  05-01-2020                    93

In [ ]:
bookseller_df.info()
bookseller_df.isnull().sum()
bookseller_df['Number of Books Sold'].describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   S.No                  366 non-null    int64
 1   Date                  366 non-null    object
 2   Number of Books Sold  366 non-null    int64
dtypes: int64(2), object(1)
memory usage: 8.7+ KB

count    366.000000
mean      94.961749
std        3.178465
min       90.000000
25%       92.000000
50%       95.000000
75%       98.000000
max      100.000000
Name: Number of Books Sold, dtype: float64

In [ ]:
total_days = len(bookseller_df)

days_geq_96 = bookseller_df[bookseller_df['Number of Books Sold'] >= 96].shape[0]


prob_geq_96 = days_geq_96 / total_days

print(f"Probability that more than or equal to 96 books will be sold on a given day: {prob_geq_96}")

Probability that more than or equal to 96 books will be sold on a given day: 0.45081967213114754

In [ ]:
# Count of days where less than or equal to 92 books were sold
days_leq_92 = bookseller_df[bookseller_df['Number of Books Sold'] <= 92].shape[0]

# Probability calculation
prob_leq_92 = days_leq_92 / total_days

print(f"Probability that less than or equal to 92 books will be sold on a given day: {prob_leq_92}")

Probability that less than or equal to 92 books will be sold on a given day: 0.27595628415300544